project:
  type: website
  output-dir: docs

website:
  site-url: https://l-ramirez-lopez.github.io
  title: "Leonardo Ramirez-Lopez"
  navbar:
    tools:
      - icon: github
        href: https://github.com/l-ramirez-lopez/
      - icon: linkedin
        href: https://linkedin.com/in/leo-ramirez-lopez
      - icon: fa brands orcid
        href: https://orcid.org/0000-0002-5369-5120
    left:
      - text: Home
        href: index.html
      - text: Research
        href: research.html
      - text: Publications
        href: publications.html
      - text: CV
        href: cv.html
      - text: Code
        href: code.html
      - text: Talks
        href: talks.html
      - text: Beyond work
        href: other.html

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false
    include-in-header:
      - ga.html
      - schema-person.html
      